## Reading Data

In [1]:
import sqlite3 as sq3
import pandas as pd
import pandas.io.sql as pds

In [2]:
path = 'data/classic_rock.db'
con = sq3.Connection(path)
con

In [3]:
query = """
SELECT * 
FROM rock_songs;
"""

observations = pds.read_sql(query, con)

observations.head()

                     Song        Artist  Release_Year  PlayCount
0        Caught Up in You   .38 Special        1982.0         82
1         Hold On Loosely   .38 Special        1981.0         85
2  Rockin' Into the Night   .38 Special        1980.0         18
3       Art For Arts Sake          10cc        1975.0          1
4              Kryptonite  3 Doors Down        2000.0         13

In [4]:
query = """
SELECT Artist, Release_Year, COUNT(*) AS num_songs, AVG(PlayCount) AS avg_plays
    FROM rock_songs
    GROUP BY Artist, Release_Year
    ORDER BY num_songs desc;
"""

observations = pds.read_sql(query, con)

observations.head()

         Artist  Release_Year  num_songs  avg_plays
0   The Beatles        1967.0         23   6.565217
1  Led Zeppelin        1969.0         18  21.000000
2   The Beatles        1965.0         15   3.800000
3   The Beatles        1968.0         13  13.000000
4   The Beatles        1969.0         13  15.000000

### Common Parameters

In [5]:
query = """
SELECT Artist, Release_Year, COUNT(*) AS num_songs, AVG(PlayCount) AS avg_plays
    FROM rock_songs
    GROUP BY Artist, Release_Year
    ORDER BY num_songs desc;
"""

observations_generator = pds.read_sql(query,
                                     con,
                                     coerce_float=True,  # Doesn't efefct this dataset, because floats were correctly parsed
                                     parse_dates=['Release_Year'],  # Parse `Release_Year` as a date
                                     chunksize=5  # Allows for streaming results as a series of shorter tables
                                     )

for index, observations in enumerate(observations_generator):
    if index < 5:
        print(f'Observation Index: {index}' .format(index))
        display(observations)

Observation Index: 0

         Artist        Release_Year  num_songs  avg_plays
0   The Beatles 1970-01-01 00:32:47         23   6.565217
1  Led Zeppelin 1970-01-01 00:32:49         18  21.000000
2   The Beatles 1970-01-01 00:32:45         15   3.800000
3   The Beatles 1970-01-01 00:32:48         13  13.000000
4   The Beatles 1970-01-01 00:32:49         13  15.000000

Observation Index: 1

         Artist        Release_Year  num_songs  avg_plays
0  Led Zeppelin 1970-01-01 00:32:50         12  13.166667
1  Led Zeppelin 1970-01-01 00:32:55         12  14.166667
2    Pink Floyd 1970-01-01 00:32:59         11  41.454545
3    Pink Floyd 1970-01-01 00:32:53         10  29.100000
4     The Doors 1970-01-01 00:32:47         10  28.900000

Observation Index: 2

          Artist        Release_Year  num_songs  avg_plays
0  Fleetwood Mac 1970-01-01 00:32:57          9  35.666667
1   Jimi Hendrix 1970-01-01 00:32:47          9  24.888889
2    The Beatles 1970-01-01 00:32:43          9   2.444444
3    The Beatles 1970-01-01 00:32:44          9   3.111111
4     Elton John 1970-01-01 00:32:53          8  18.500000

Observation Index: 3

           Artist        Release_Year  num_songs  avg_plays
0    Led Zeppelin 1970-01-01 00:32:51          8  47.750000
1    Led Zeppelin 1970-01-01 00:32:53          8  34.125000
2          Boston 1970-01-01 00:32:56          7  69.285714
3  Rolling Stones 1970-01-01 00:32:49          7  36.142857
4       Van Halen 1970-01-01 00:32:58          7  51.142857

Observation Index: 4

                         Artist        Release_Year  num_songs  avg_plays
0             Bruce Springsteen 1970-01-01 00:32:55          6   7.666667
1             Bruce Springsteen 1970-01-01 00:33:04          6  11.500000
2  Creedence Clearwater Revival 1970-01-01 00:32:49          6  23.833333
3  Creedence Clearwater Revival 1970-01-01 00:32:50          6  18.833333
4                   Def Leppard 1970-01-01 00:33:07          6  32.000000

### SQLite Master Tables

In [6]:
path = 'data/baseball.db'
con = sq3.Connection(path)

query = """
SELECT * 
FROM allstarfull;
"""

allstar_observations = pd.read_sql(query, con)
allstar_observations

,index,playerID,yearID,gameNum,gameID,teamID,lgID,GP,startingPos
0,0,gomezle01,1933,0,ALS193307060,NYA,AL,1.0,1.0
1,1,ferreri01,1933,0,ALS193307060,BOS,AL,1.0,2.0
2,2,gehrilo01,1933,0,ALS193307060,NYA,AL,1.0,3.0
3,3,gehrich01,1933,0,ALS193307060,DET,AL,1.0,4.0
4,4,dykesji01,1933,0,ALS193307060,CHA,AL,1.0,5.0
...,...,...,...,...,...,...,...,...,...
5143,5143,seageco01,2016,0,ALS201607120,LAN,NL,1.0,NaN
5144,5144,strasst01,2016,0,ALS201607120,WAS,NL,0.0,NaN
5145,5145,syndeno01,2016,0,ALS201607120,NYN,NL,0.0,NaN
5146,5146,teherju01,2016,0,ALS201607120,ATL,NL,1.0,NaN
5147,5147,zobribe01,2016,0,ALS201607120,CHN,NL,1.0,4.0

In [7]:
# Create a variable, tables, which reads in all data from the table sqlite_master
all_tables = pd.read_sql('SELECT * FROM sqlite_master', con)
all_tables

,type,name,tbl_name,rootpage,sql
0,table,allstarfull,allstarfull,2,"CREATE TABLE ""allstarfull"" (\n""index"" INTEGER,..."
1,index,ix_allstarfull_index,allstarfull,3,"CREATE INDEX ""ix_allstarfull_index""ON ""allstar..."
2,table,schools,schools,26,"CREATE TABLE ""schools"" (\n""index"" INTEGER,\n ..."
3,index,ix_schools_index,schools,31,"CREATE INDEX ""ix_schools_index""ON ""schools"" (""..."
4,table,batting,batting,99,"CREATE TABLE ""batting"" (\n""index"" INTEGER,\n ..."
5,index,ix_batting_index,batting,100,"CREATE INDEX ""ix_batting_index""ON ""batting"" (""..."

In [8]:
best_query = """
SELECT playerID, sum(GP) AS num_games_played, AVG(startingPos) AS avg_starting_position
    FROM allstarfull
    GROUP BY playerID
    ORDER BY num_games_played DESC, avg_starting_position ASC
    LIMIT 3
"""

best = pd.read_sql(best_query, con)
best

    playerID  num_games_played  avg_starting_position
0  musiast01              24.0               6.357143
1   mayswi01              24.0               8.000000
2  aaronha01              24.0               8.470588